### PR TITLE
Move .nuspec and tools into src directory

### LINKED ISSUE #25: latest release has .git folder
It's just the repository contents, but really it's not necessary.

Let's see if I can put together an update to remove it.

### PR DESCRIPTION
**Pull request by flcdrg**
Prevents choco pack from including more than we want (eg. .git directory)

Resolves #25

### CODE REVIEW

**Comment by shiftkey** [comment]
@flcdrg we still have the original `beyondcompare.nuspec` file at the root of the repository - is it worth removing that here?

**Comment by flcdrg** [comment]
argh.. I moved it, but then reverted that because I tried to unchange the contents :-(

**Comment by flcdrg** [comment]
Ok.. that should be better

**Comment by shiftkey** [comment]
@flcdrg thanks for spotting this (and submitting the fix)!

**Pull request merged**
